// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

/*
Package go_micro_srv_user is a generated protocol buffer package.

It is generated from these files:
	proto/user/user.proto

It has these top-level messages:
	User
	Request
	Response
	Token
	Error
*/
package go_micro_srv_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Company  string `protobuf:"bytes,3,opt,name=company" json:"company,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Response struct {
	User   *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Users  []*User  `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Token struct {
	Token  string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Valid  bool     `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code        int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.user.User")
	proto.RegisterType((*Request)(nil), "go.micro.srv.user.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user.Response")
	proto.RegisterType((*Token)(nil), "go.micro.srv.user.Token")
	proto.RegisterType((*Error)(nil), "go.micro.srv.user.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	ValidateUserToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.user"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.GetAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Auth", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ValidateUserToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.ValidateUserToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Create(context.Context, *User, *Response) error
	Get(context.Context, *User, *Response) error
	GetAll(context.Context, *Request, *Response) error
	Auth(context.Context, *User, *Response) error
	ValidateUserToken(context.Context, *Token, *Token) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) Create(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.Create(ctx, in, out)
}

func (h *UserService) Get(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.Get(ctx, in, out)
}

func (h *UserService) GetAll(ctx context.Context, in *Request, out *Response) error {
	return h.UserServiceHandler.GetAll(ctx, in, out)
}

func (h *UserService) Auth(ctx context.Context, in *User, out *Response) error {
	return h.UserServiceHandler.Auth(ctx, in, out)
}

func (h *UserService) ValidateUserToken(ctx context.Context, in *Token, out *Token) error {
	return h.UserServiceHandler.ValidateUserToken(ctx, in, out)
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0x6e, 0xf3, 0xd7, 0xf6, 0x14, 0x2e, 0x74, 0xb8, 0x97, 0x3b, 0xc4, 0x4d, 0xc9, 0x4a, 0x10,
	0xa3, 0xd4, 0x75, 0xc5, 0x52, 0xa4, 0xb8, 0x8d, 0x3f, 0xfb, 0x98, 0x1c, 0x74, 0x30, 0xc9, 0xc4,
	0x99, 0x69, 0xc4, 0x37, 0xf1, 0xe9, 0x7c, 0x16, 0x99, 0x93, 0x56, 0x04, 0x53, 0x85, 0x6e, 0xda,
	0xf3, 0xfd, 0x24, 0xf3, 0xcd, 0xf9, 0x08, 0xfc, 0xab, 0x95, 0x34, 0xf2, 0x64, 0xad, 0x51, 0xd1,
	0x4f, 0x4c, 0x98, 0x4d, 0x1e, 0x64, 0x5c, 0x8a, 0x4c, 0xc9, 0x58, 0xab, 0x26, 0xb6, 0x42, 0xd4,
	0x80, 0x77, 0xab, 0x51, 0xb1, 0x3f, 0xe0, 0x88, 0x9c, 0xf7, 0xa7, 0xfd, 0xc3, 0x51, 0xe2, 0x88,
	0x9c, 0x31, 0xf0, 0xaa, 0xb4, 0x44, 0xee, 0x10, 0x43, 0x33, 0xe3, 0x30, 0xc8, 0x64, 0x59, 0xa7,
	0xd5, 0x2b, 0x77, 0x89, 0xde, 0x42, 0xf6, 0x17, 0x7c, 0x2c, 0x53, 0x51, 0x70, 0x8f, 0xf8, 0x16,
	0xb0, 0x10, 0x86, 0x75, 0xaa, 0xf5, 0x8b, 0x54, 0x39, 0xf7, 0x49, 0xf8, 0xc4, 0xd1, 0x08, 0x06,
	0x09, 0x3e, 0xaf, 0x51, 0x9b, 0xe8, 0xad, 0x0f, 0xc3, 0x04, 0x75, 0x2d, 0x2b, 0x8d, 0xec, 0x08,
	0x3c, 0x9b, 0x8b, 0x92, 0x8c, 0x67, 0xff, 0xe3, 0x6f, 0x89, 0x63, 0x1b, 0x37, 0x21, 0x13, 0x3b,
	0x06, 0xdf, 0xfe, 0x6b, 0xee, 0x4c, 0xdd, 0x9f, 0xdc, 0xad, 0x8b, 0x9d, 0x42, 0x80, 0x4a, 0x49,
	0xa5, 0xb9, 0x4b, 0x7e, 0xde, 0xe1, 0xbf, 0xb4, 0x86, 0x64, 0xe3, 0x8b, 0x10, 0xfc, 0x1b, 0xf9,
	0x84, 0x95, 0xbd, 0xa0, 0xb1, 0xc3, 0x66, 0x43, 0x2d, 0xb0, 0x6c, 0x93, 0x16, 0x22, 0xa7, 0x2d,
	0x0d, 0x93, 0x16, 0xec, 0x71, 0xcc, 0x1c, 0x7c, 0x22, 0xec, 0xd6, 0x33, 0x99, 0x23, 0x9d, 0xe2,
	0x27, 0x34, 0xb3, 0x29, 0x8c, 0x73, 0xd4, 0x99, 0x12, 0xb5, 0x11, 0xb2, 0xda, 0x14, 0xf2, 0x95,
	0x9a, 0xbd, 0x3b, 0x30, 0xb6, 0xf7, 0xbc, 0x46, 0xd5, 0x88, 0x0c, 0xd9, 0x05, 0x04, 0x4b, 0x85,
	0xa9, 0x41, 0xb6, 0x6b, 0x23, 0xe1, 0x41, 0x87, 0xb0, 0xed, 0x20, 0xea, 0xb1, 0x39, 0xb8, 0x2b,
	0x34, 0x7b, 0x3f, 0xbe, 0x84, 0x60, 0x85, 0x66, 0x51, 0x14, 0x2c, 0xec, 0x34, 0x52, 0xef, 0xbf,
	0xbd, 0xe4, 0x1c, 0xbc, 0xc5, 0xda, 0x3c, 0xee, 0x1d, 0xe2, 0x0a, 0x26, 0x77, 0xb6, 0x8f, 0xd4,
	0xa0, 0xb5, 0xb7, 0x3d, 0x76, 0x75, 0x41, 0x4a, 0xb8, 0x53, 0x89, 0x7a, 0xf7, 0x01, 0x7d, 0x3e,
	0x67, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x40, 0xec, 0xee, 0x29, 0x57, 0x03, 0x00, 0x00,
}
